### PR TITLE
Add basic Float support

### PR DESCRIPTION
**Pull request by turboladen**
I'm looking to add wrapper functions in ruru, but needed these guys first. I broke the mould and added a couple tests--probably not the purest of tests, but they seem better than none.

### CODE REVIEW

**Comment by turboladen** [comment]
I'm not too sure about those travis failures. Am I, perhaps missing some implementation stuff? I'm on OSX Sierra and they seem alright over here...

**Comment by d-unsed** [comment]
I think the problem is that current Travis setup for `ruby-sys` lacks some configuration for ruby. Also every test will require to launch VM (`vm::ruby_init()`).

I've updated `.travis.yml`. Can you please rebase on top of master and add `vm::ruby_init()`?

**Comment by turboladen** [comment]
Thanks for that, @d-unseductable. I wonder why just the failures with 2.3.1? I'll poke around ruby's source and see if I can find any differences. I've been testing with 2.2.5 locally, so I'll get 2.3.1 going here too.

**Comment by turboladen** [comment]
Looks like 2.3.1 defines an `RFloat` struct ([here](https://github.com/ruby/ruby/blob/v2_3_1/internal.h#L393)). I wasn't able to figure out when that got introduced, but I do see it getting moved from `ruby.h` to `internal.h` [here](https://github.com/ruby/ruby/commit/6adcf6a898cd8d6becfebd0ee1a881e9bc77c3be#diff-5a7b7a4b0ceae44c9fd2190fb68187fe). Couldn't find it in 2.3.0 either. I'll see if I can figure out how to wrap that with rust, but... do you know if there's a safe way to check the ruby version we're using from rust code?

**Comment by turboladen** [comment]
Check that--I forget that github's search only searches the current main branch, not your currently selected branch. I _don't_ see the `RFloat` struct in 2.3.1.

**Comment by d-unsed** [comment]
@turboladen I've just played a bit with the code.

The tests failed randomly and with different kinds of errors. That was a sign of some concurrency problems in the MRI VM 😄 

`cargo test` runs a test suite in multiple threads. But the program which uses the VM must have only one thread due to MRI limitations (there are exceptions though like `rb_thread_call_without_gvl` which releases GVL for current thread). Unfortunately `RUST_TEST_TASKS=1 cargo test` does not help in this case.

The reason why tests in ruru work fine is that ruru uses doctests which are run in single-threaded mode.

These bindings look correct, so I suggest to remove tests, merge the PR and have some higher-level doctests in the ruru crate.

**Comment by turboladen** [comment]
Interesting! And totally makes sense. I, however, just managed to spill a bottle of water on my laptop so it make be a couple days before I get back on this. 😞

**Comment by d-unsed** [comment]
Oh :(

If you want, I can remove the tests myself. What do you think?

**Comment by turboladen** [comment]
Ok, tests removed.

**Comment by turboladen** [comment]
Actually, it looks like all is well! I should be able to get to this some time today.

**Comment by d-unsed** [comment]
Thank you @turboladen!

**Comment by turboladen** [comment]
🎉

**Comment by d-unsed** [comment]
I've released these changes with `0.2.16`. Would you like to work on implementing `Float` in ruru?

**Comment by turboladen** [comment]
Sure!

**Pull request merged**
